---
version: '3.6'
services:
  ptsooy:
    image: pablogomez/ptsooy
    container_name: ptsooy
    environment:
      - date_after=20200731
      - vids_count=3
      - host=https://ptsooy.example.com
      - keep_newer_than=0 # days, 0 keeps all
    volumes:
      - /path/to/subscription_manager:/app/subscription_manager
      - /path/to/Videos/:/app/Videos/
    restart: unless-stopped

  ptsooy-webserver:
    build: ~/config/ptsooy/.
    container_name: ptsooy-webserver
    volumes:
      - /path/to/Videos/:/usr/share/nginx/html:ro
    ports:
      - 80:8080